<a href="https://colab.research.google.com/github/luis-jaramillo-talentotech/Talento_Tech_Analisis_de_datos_Basico/blob/main/Laboratorio_7_Parte_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

-	Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo.

In [14]:
import numpy as np
arr = np.linspace(1,10,10)
print("El arreglo es:",arr)
print("La suma de los valores del arreglo es:", arr.sum())
print("La media de los valores del arreglo es:", arr.mean())
print("El máximo valor de los valores del arreglo es:", arr.max())

El arreglo es: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
La suma de los valores del arreglo es: 55.0
La media de los valores del arreglo es: 5.5
El máximo valor de los valores del arreglo es: 10.0


-	Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6

In [16]:
import numpy as np
arr = np.zeros((3,4))
print("Arreglo de 3x4:",arr,sep="\n")
arr = arr.reshape((2, 6))
print("Arreglo de 2x6:",arr,sep="\n")

Arreglo de 3x4:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Arreglo de 2x6:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


-	Generar una matriz aleatoria de 3x3 y calcular su transpuesta.

In [18]:
import numpy as np
arr = np.random.randint(1,100,size=(3,3))
print("Arreglo de 3x3:",arr,sep="\n")
print("Transpuesta del arreglo:",arr.T,sep="\n")

Arreglo de 3x3:
[[20 40 70]
 [13 23 27]
 [68 22 15]]
Transpuesta del arreglo:
[[20 13 68]
 [40 23 22]
 [70 27 15]]
